const BARAJAS = [
  { Nombre: "El Gallo", urlImagen: "../assets/img/01-ElGallo.jpg" },
  { Nombre: "El Diablito", urlImagen: "../assets/img/02-ElDiablo.jpg" },
  { Nombre: "La Dama", urlImagen: "../assets/img/03-LaDama.jpg" },
  { Nombre: "El Catrin", urlImagen: "../assets/img/04-Catrin.jpg" },
  { Nombre: "El Paraguas", urlImagen: "../assets/img/05-Paraguas.jpg" },
  { Nombre: "La Sirena", urlImagen: "../assets/img/06-Sirena.jpg" },
  { Nombre: "La Escalera", urlImagen: "../assets/img/07-Escalera.jpg" },
  { Nombre: "La Botella", urlImagen: "../assets/img/08-Botella.jpg" },
  { Nombre: "El Barril", urlImagen: "../assets/img/09-Barril.jpg" },
  { Nombre: "El Arbol", urlImagen: "../assets/img/10-Arbol.jpg" },
  { Nombre: "El Melon", urlImagen: "../assets/img/11-Melon.jpg" },
  { Nombre: "El Valiente", urlImagen: "../assets/img/12-Valiente.jpg" },
  { Nombre: "El Gorrito", urlImagen: "../assets/img/13-Gorrito.jpg" },
  { Nombre: "La Muerte", urlImagen: "../assets/img/14-Muerte.jpg" },
  { Nombre: "La Pera", urlImagen: "../assets/img/15-Pera.jpg" },
  { Nombre: "La Bandera", urlImagen: "../assets/img/16-Bandera.jpg" },
  { Nombre: "El Bandolon", urlImagen: "../assets/img/17-Bandolon.jpg" },
  { Nombre: "El Violoncello", urlImagen: "../assets/img/18-Violincello.jpg" },
  { Nombre: "La Garza", urlImagen: "../assets/img/19-Garza.jpg" },
  { Nombre: "El Pajaro", urlImagen: "../assets/img/20-Pajaro.jpg" },
  { Nombre: "La Mano", urlImagen: "../assets/img/21-Mano.jpg" },
  { Nombre: "La Bota", urlImagen: "../assets/img/22-Bota.jpg" },
  { Nombre: "La Luna", urlImagen: "../assets/img/23-Luna.jpg" },
  { Nombre: "El Cotorro", urlImagen: "../assets/img/24-Bota.jpg" },
  { Nombre: "El Borracho", urlImagen: "../assets/img/25-Borracho.jpg" },
  { Nombre: "El Negrito", urlImagen: "../assets/img/26-negrito.jpg" },
  {Nombre: "El Corazón", urlImagen: "../assets/img/27-corazon.jpg"},
  {Nombre: "La Sandía", urlImagen: "../assets/img/28-sandia.jpg"},
  {Nombre: "El Tambor", urlImagen: "../assets/img/29-tambor.jpg"},
  {Nombre: "El Camarón", urlImagen: "../assets/img/30-camaron.jpg"},
  {Nombre: "Las Jaras", urlImagen: "../assets/img/31-jaras.jpg"},
  {Nombre: "El Músico", urlImagen: "../assets/img/32-musico.jpg"},
  {Nombre: "La Araña",urlImagen: "../assets/img/33-araña.jpg"},
  {Nombre: "El Soldado", urlImagen: "../assets/img/34-soldado.jpg"},
  {Nombre: "La Estrell", urlImagen: "../assets/img/35-estrella.jpg"},
  {Nombre: "El Cazo", urlImagen: "../assets/img/36-cazo.jpg"},
  {Nombre: "El Mundo",urlImagen: "../assets/img/37-mundo.jpg"},
  {Nombre: "El Apache", urlImagen: "../assets/img/38-apache.jpg"},
  {Nombre: "El Nopal",urlImagen: "../assets/img/39-nopal.jpg"},
  {Nombre: "El Alacrán", urlImagen: "../assets/img/40-alacran.jpg"},
  {Nombre: "La Rosa", urlImagen: "../assets/img/41-rosa.jpg"},
  {Nombre: "La Calaver", urlImagen: "../assets/img/43-campana.jpg"},
  {Nombre: "La Campana", urlImagen: "../assets/img/44-cantarito.jpg"},
  {Nombre: "El Cantario", urlImagen: "../assets/img/45-venado.jpg"},
  {Nombre: "El Venado", urlImagen: "../assets/img/46-sol.jpg"},
  {Nombre: "El Sol", urlImagen: "../assets/img/47-coronajpg.jpg"},
  {Nombre: "La Corona", urlImagen: "../assets/img/47-corona.jpg"},
  {Nombre: "La Chalupa", urlImagen: "../assets/img/48-chalupa.jpg"},
  {Nombre: "El Pino", urlImagen: "../assets/img/49-pino.jpg"},
  {Nombre: "El Pescado", urlImagen: "../assets/img/50-pescado.jpg"},
  {Nombre: "La Palma",urlImagen: "../assets/img/51-palma.jpg"},
  {Nombre: "La Maceta", urlImagen: "../assets/img/52-maceta.jpg"},
  {Nombre: "El Arpa", urlImagen: "../assets/img/53-arpa.jpg"},
  {Nombre: "La Rana", urlImagen: "../assets/img/54-rana.jpg"}
];
